name: Java CI Schedule

on:
  push:
    branches: [ "master" ]

concurrency:
  group: 'master'
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
    strategy:
      matrix:
        java: [ '17' ]

    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: "temurin"

      - name: Verify
        id: verify
        run: ./gradlew test --tests "HomeTests"

      - name: install playwright
        if: steps.verify.outputs.result == 'failure'
        run: ./gradlew installPlaywright --args="install --with-deps"

      - name: Gradle Test
        id: test
        continue-on-error: true
        run: ./gradlew test

      - uses: codecov/codecov-action@v5
        with:
          files: ./build/reports/jacoco/test/jacocoTestReport.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

